const brandLinks = {'ITC':'https://www.itchotels.com/in/en/itcgrandchola-chennai?utm_source=bing&utm_medium=cpc&utm_campaign=HQ|ITC|ITC_Grand_Chola|Brand|Exact|Bing&msclkid=1db2b7118ed01a568453d3e75de04fc7',
            'Lakme':'https://www.lakmeindia.com/',
            'Zoom':'https://www.zoomcar.com/in/',
            'Zomato':'https://www.zomato.com/chennai/east-coast-at-madras-square-neelangarai',
            'Trends':'https://trends.ajio.com/',
            'Indian Accent':'https://www.indianaccent.com/',
            'Puma':'https://in.puma.com/in/en?msclkid=d8f764ffab161f55566700097fbfab45&utm_aud=OTH&utm_campaign=BS_BNG_SEA-TXT_Brand-Exact&utm_medium=BS&utm_obj=CONV&utm_source=BNG-SEA-TXT',
            'Adidas':'https://www.adidas.co.in/',
            'Saravana Stores':'https://www.subway.com/',
            'Blinkit':'https://blinkit.com/',
            'KFC':'https://online.kfc.co.in/',
            'Spice Jet':'https://www.spicejet.com/',
            'City Home':'https://www.booking.com/hotel/in/city-home-chennai.en-gb.html?aid=356980&label=gog235jc-1DCAsobEIRY2l0eS1ob21lLWNoZW5uYWlIM1gDaGyIAQGYAQm4ARfIAQzYAQPoAQGIAgGoAgO4AuSn26cGwAIB0gIkZTBhZTdmOWMtNzU2NS00OWU1LWE4ZjEtMGVlMDIxMzc1Nzhi2AIE4AIB&dist=0&keep_landing=1&sb_price_type=total&type=total&',
            'Swiggy':'https://www.swiggy.com/',
            'Tommy Hilfiger':'https://tommyhilfiger.nnnow.com/',
            'Bukhara':'https://amazon.com/',
            'Pizza Hut':'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwi9kPCF9pKBAxX8gUsFHYs2C7wYABAAGgJzZg&ase=2&gclid=CjwKCAjwo9unBhBTEiwAipC113N2IY8WEAZsMssQbT7tr6mHH6Me87RuAx4tkYKhI_URWsiim7XSzRoCQ-IQAvD_BwE&ohost=www.google.com&cid=CAESa-D2JtqZYjQs0ccgfECg_OCdCKI0vtfiD4kLXnQtciK4rzMQ9_uR4sSEiY016P5PUwA1T4SaxrYww9neHpCdDW6Ib1C14eiqABY6awpJ8TbynTaFgZODgaakHOdPxwfLztqGvxeOUMIgg_vl&sig=AOD64_0rPUKV7rHcytXfDiJyQbeikR472A&q&nis=4&adurl&ved=2ahUKEwjDpuOF9pKBAxVISGwGHTiVAfYQ0Qx6BAgQEAM',
            'Subway':'https://www.subway.com/',
            'Dominos':'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwifhtL59ZKBAxVcmWYCHfFmAuAYABAAGgJzbQ&ase=2&gclid=CjwKCAjwo9unBhBTEiwAipC113I_7fGzBvKTjQ0-cxzlaMKecVVYslv_mIy5QkZl8sK__k7kI3ZI3xoCz1wQAvD_BwE&ohost=www.google.com&cid=CAESa-D2GDZOwtVc24-XtO22rcQRlsfQG8F9kDNTUkxEqdq0exOLzow5ZwopgIlNWVUiEYp3kWm6UpfGNzL7YsYos8wfCSFgMpMF7JOcX1RDNX128fogo9-yv0eoSzuvA5n8W92Zls-K3kWrI_GT&sig=AOD64_2A0HTB6SdX_anCDYRS9QPAX2Tpxg&q&nis=4&adurl&ved=2ahUKEwjS7Mb59ZKBAxVgSmwGHQ12BtYQ0Qx6BAgQEAE',
            'Higginbothams Bookstore':'https://amazon.com/',
            'Bahrisons':'https://www.booksatbahri.com/',
            'Skinn':'https://www.skinn.in/',
            'Indigo':'https://www.goindigo.in/',
            'Holiday Inn':'https://www.ihg.com/holidayinn/hotels/us/en/reservation',
            'U S Polo':'https://uspoloassn.in/?utm_source=google&utm_medium=cpc&utm_campaign=SB_Google_USPA_IN_Web_Search&utm_id=20357717272&utm_device=c&utm_target=&utm_term=us%20polo&gclid=CjwKCAjwo9unBhBTEiwAipC110U-E-tbI2ee825qW17m7Es2dwS3JClqXgeTxg9-faRZLnVQ7sPpsRoCn6QQAvD_BwE',
            'East Coast at Madras Square':'https://www.zomato.com/chennai/east-coast-at-madras-square-neelangarai',
            'BookmyShow':'https://in.bookmyshow.com/explore/home/chennai'
            } 